[package]
name = "genpay-parse-two"
version = "0.1.0"
edition = "2024"

[dependencies]
genpay-lexer = { path = "../genpay-lexer" }
miette = { version = "7.5.0", features = ["fancy"] }
thiserror = "2.0.12"
indexmap = "2.9.0"
