permissions:
  contents: write

name: Build GenPay Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: deen-linux-x86_64
            binary: deen
          - target: aarch64-apple-darwin
            os: macos-latest
            name: deen-macos-aarch64
            binary: deen
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: deen-windows-x86_64
            binary: deen.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    # Linux dependencies
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-18-dev libclang-18-dev clang-18 libpolly-18-dev
        echo "LLVM_SYS_180_PREFIX=/usr/lib/llvm-18" >> $GITHUB_ENV

    # macOS dependencies
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install llvm@18 zstd libffi
        LLVM_PREFIX=$(brew --prefix llvm@18)
        echo "LLVM_SYS_180_PREFIX=$LLVM_PREFIX" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$LLVM_PREFIX/lib:$(brew --prefix zstd)/lib:$(brew --prefix libffi)/lib:$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$LLVM_PREFIX/lib:$(brew --prefix zstd)/lib:$(brew --prefix libffi)/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$LLVM_PREFIX/lib/pkgconfig:$(brew --prefix zstd)/lib/pkgconfig:$(brew --prefix libffi)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "RUSTFLAGS=-L$LLVM_PREFIX/lib" >> $GITHUB_ENV

    # Windows dependencies
    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      run: |
        curl -L -o llvm.tar.xz https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-pc-windows-msvc.tar.xz
        7z x llvm.tar.xz
        7z x llvm.tar -oC:\
        move "C:\clang+llvm-18.1.8-x86_64-pc-windows-msvc" "C:\llvm"
        
    - name: Set Windows LLVM environment
      if: matrix.os == 'windows-latest'
      run: |
        echo "LLVM_SYS_180_PREFIX=C:\llvm" >> $env:GITHUB_ENV
        echo "PATH=C:\llvm\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Prepare binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cp target/${{ matrix.target }}/release/${{ matrix.binary }} ${{ matrix.name }}
        chmod +x ${{ matrix.name }}

    
