- name: Download and install LLVM 18
  run: |
    LLVM_VERSION="18.1.7"
    if [[ "$(uname -m)" == "arm64" ]]; then
      LLVM_FILE="clang+llvm-${LLVM_VERSION}-arm64-apple-darwin22.0.tar.xz"
    else
      LLVM_FILE="clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin.tar.xz"
    fi
    LLVM_URL="https://github.com/llvm/llvm-project/releases/download/llvmorg-${LLVM_VERSION}/${LLVM_FILE}"

    curl -L "$LLVM_URL" | tar Jxf -
    echo "$(pwd)/clang+llvm-${LLVM_VERSION}-*" >> $GITHUB_PATH
