name: Deploy Rust Documentation

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'
        type: string
      include_private:
        description: 'Include private items in documentation'
        required: false
        default: true
        type: boolean
      clean_cache:
        description: 'Clean cargo cache before build'
        required: false
        default: false
        type: boolean

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Clean cache
      if: ${{ github.event.inputs.clean_cache == 'true' }}
      run: cargo clean
    
    - name: Cache dependencies
      if: ${{ github.event.inputs.clean_cache != 'true' }}
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Build documentation (with private items)
      if: ${{ github.event.inputs.include_private != 'false' }}
      run: |
        cargo doc --document-private-items
        echo '<meta http-equiv="refresh" content="0; url=deen/">' > target/doc/index.html
    
    - name: Build documentation (public only)
      if: ${{ github.event.inputs.include_private == 'false' }}
      run: |
        cargo doc
        echo '<meta http-equiv="refresh" content="0; url=deen/">' > target/doc/index.html
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './target/doc'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
