name: Build with LLVM 18

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14 # Or macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set LLVM version and download URL
      id: llvm_vars
      run: |
        echo "LLVM_VERSION=18.1.7" >> $GITHUB_ENV
        echo "LLVM_ARCH=arm64-apple-darwin22" >> $GITHUB_ENV # Use arm64-apple-darwin22 for macOS-14
        echo "LLVM_URL=https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.7/clang+llvm-18.1.7-arm64-apple-darwin22.tar.xz" >> $GITHUB_ENV

    - name: Download LLVM 18 binaries
      run: |
        curl -L ${{ env.LLVM_URL }} -o llvm.tar.xz
        
  
