name: Build with LLVM 18

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14 # Or macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set LLVM version and download URL
      id: llvm_vars
      run: |
        echo "LLVM_VERSION=18.1.7" >> $GITHUB_ENV
        echo "LLVM_ARCH=arm64-apple-darwin22" >> $GITHUB_ENV # Use arm64-apple-darwin22 for macOS-14
        echo "LLVM_URL=https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.7/clang+llvm-18.1.7-arm64-apple-darwin22.tar.xz" >> $GITHUB_ENV

    - name: Download LLVM 18 binaries
      run: |
        curl -L ${{ env.LLVM_URL }} -o llvm.tar.xz
        
    - name: Extract LLVM 18 binaries
      run: |
        mkdir -p ${{ github.workspace }}/llvm
        tar -xf llvm.tar.xz -C ${{ github.workspace }}/llvm --strip-components=1

    - name: Add LLVM 18 to PATH
      run: |
        echo "${{ github.workspace }}/llvm/bin" >> $GITHUB_PATH
        echo "LLVM_PATH=${{ github.workspace }}/llvm" >> $GITHUB_ENV
        
    - name: Verify LLVM installation
      run: |
        clang++ --version
        
    - name: Build and run your project
      # Replace this with your actual build commands
      run: |
        clang++ 
